include:
    - .docker/compose/infra.yaml
    - .docker/compose/app.yaml
    - .docker/compose/nginx.yaml


services:
    app:
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
            gotenberg:
                condition: service_healthy

    nginx:
        depends_on:
            app:
                condition: service_healthy

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - matrix_network
